openapi: 3.0.3
info:
  title: blog
  version: 1.0.0
  description: ブログ記事操作API
paths:
  /entries/:
    post:
      operationId: article_create
      description: 記事を投稿するAPI
      summary: ブログ記事投稿API
      tags:
      - ブログ全体
      responses:
        '200':
          description: '成功'
        '400':
          description: "存在しないユーザーID/status"
    get:
      operationId: articles_get
      description: 全てのブログ記事を取得する
      summary: 全てのブログ記事取得API
      parameters:
      - in: query
        name: article_id
        description: 記事のID
        schema:
          type: integer
      tags:
      - ブログ全体
      responses:
        '200':
          description: '成功'
        '400':
          description: '存在しない記事ID'
servers:
- url: http://127.0.0.1:8000/v1/api/
  description: Local
