# Generated by Django 3.2.7 on 2021-09-13 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='article_id',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
