# Generated by Django 3.2.7 on 2021-09-15 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_entry_article_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='test1',
            field=models.TextField(default='7923y7', verbose_name='テスト'),
        ),
    ]
