# Generated by Django 3.2.7 on 2021-09-15 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_entry_test1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='test1',
        ),
    ]
